Access the Map, View and Fail Samples migrated to React Function Component
Esri/react-arcgis pull request #239
Opened 2022-07-01 08:22 UTC by cemrehancavdar

This PR includues 2 basic code sample changes on Markdown.md.
Access the Map, View sample and onFail sample migrated from Class Component to Function Component (which all other samples uses Function Component structure)

2022-07-01 19:28 UTC, gavinr requested changes
Thanks. Overall these changes to the README samples look good, just one small tweak I noticed.

2022-07-01 19:28 UTC, gavinr commented on README.md
> +    const {status, setStatus} = useState('loading');
```suggestion
    const [status, setStatus] = useState('loading');

```

2022-07-02 04:41 UTC, cemrehancavdar commented
Oh, i see! Commited it.
Thank you 👍

2022-07-02 14:26 UTC, gavinr approved these changes

2022-07-02 19:06 UTC, cemrehancavdar commented
Can you merge it? @gavinr

2022-07-07 15:54 UTC, tomwayson reviewed
My intention was to have _both_ class and functional component examples. It seems to me like there is still value in that.

2022-07-07 22:40 UTC, tomwayson commented
Thank you @cemrehancavdar, but I am closing this as we are now archiving this repo

2022-07-07 22:40 UTC, closed without merging